applySceneGeometryPerSession('MELA_0215', 4, 'resume', true)
applySceneGeometryPerSession('MELA_0177', 4, 'resume', true)
applySceneGeometryPerSession('MELA_0216', 1, 'resume', true)
applySceneGeometryPerSession('MELA_0170', 1, 'resume', true)
applySceneGeometryPerSession('MELA_0170', 2, 'resume', true)
applySceneGeometryPerSession('MELA_0170', 3, 'resume', true)
applySceneGeometryPerSession('MELA_0170', 4, 'resume', true)