applySceneGeometryPerSession('MELA_0215', 1, 'resume', true)
applySceneGeometryPerSession('MELA_0177', 3, 'resume', true)
applySceneGeometryPerSession('MELA_0221', 4, 'resume', true)
applySceneGeometryPerSession('MELA_0219', 4, 'resume', true)
applySceneGeometryPerSession('MELA_0171', 1, 'resume', true)
applySceneGeometryPerSession('MELA_0171', 2, 'resume', true)
applySceneGeometryPerSession('MELA_0171', 3, 'resume', true)
applySceneGeometryPerSession('MELA_0171', 4, 'resume', true)
